### ISSUE TITLE
Cursor error in flatpak version

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [flathub/org.audacityteam.Audacity#53] opened 2020-07-19 21:35 UTC
Hi, for some reason, there is this stranger error in the audacity cursor the flatpak version. I also have the snap version and it's works fine.

I'm using KDE Neon 5.19; Flatpak 1.6.2; Audacity 2.4.2

I tried many themes gtk themes and the error still in all of them.
![Screenshot_20200719_180553](https://user-images.githubusercontent.com/12240167/87885809-8b054800-c9ee-11ea-9f85-f554454945c3.png)
![Screenshot_20200719_180542](https://user-images.githubusercontent.com/12240167/87885810-8f316580-c9ee-11ea-85d9-4784337718d8.png)

**Comment by ViniciusBRodrigues** [comment] 2020-07-19 21:52
Workaround:

I changed the exec command in: **/var/lib/flatpak/app/org.audacityteam.Audacity/current/active/export/share/applications/org.audacityteam.Audacity** to **flatpak run --runtime=org.gnome.Platform//3.36 org.audacityteam.Audacity**

**Comment by ViniciusBRodrigues** [comment] 2020-07-19 22:07
And now, there is no sound in my computer anymore, in my phones or hmdi output.

**Comment by oshodisa** [comment] 2020-07-22 14:25
Hi,

I may have the same issue as you.

The cursor representing the play head (when not pinned) does not move when playing audio.  You do occasionally see jitters or jumping of the line, but not consistently.

I thought I had found a fix, but was advised it was an issue with teh flatpak build, and not audacity itself?  Don't know if that rings true for you but your note that Snap works but not flatpak would support this.

I'm trying to use Audacity 2.4.2 on a chrome OS via Linux.

I feel like I'm almost there but falling over at the last hurdle.  Any hints/suggestions would be welcome.

cheers
(didn't want to start a new topic if my issue is the same as yours)

**Comment by ViniciusBRodrigues** [comment] 2020-07-22 17:32
> Hi,
> 
> I may have the same issue as you.
> 
> The cursor representing the play head (when not pinned) does not move when playing audio. You do occasionally see jitters or jumping of the line, but not consistently.
> 
> I thought I had found a fix, but was advised it was an issue with teh flatpak build, and not audacity itself? Don't know if that rings true for you but your note that Snap works but not flatpak would support this.
> 
> I'm trying to use Audacity 2.4.2 on a chrome OS via Linux.
> 
> I feel like I'm almost there but falling over at the last hurdle. Any hints/suggestions would be welcome.
> 
> cheers
> (didn't want to start a new topic if my issue is the same as yours)

Hi, I gave up and installed the Snap version.

**Comment by Unrud** [comment] 2020-08-17 18:47
Duplicate of https://github.com/flathub/org.audacityteam.Audacity/issues/34

**Closed** 2020-10-04 18:40 UTC
