### ISSUE TITLE
graphical bug XFCE

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/org.audacityteam.Audacity#35] opened 2019-06-12 23:25 UTC
graphical bug when maximized and mouse XFCE (Fedora 30)

flatpak info org.audacityteam.Audacity

Audacity - Record and edit audio files

          ID: org.audacityteam.Audacity
         Ref: app/org.audacityteam.Audacity/x86_64/stable
        Arq.: x86_64
        Ramo: stable
     Version: 2.3.0
     License: GPL-2.0 and CC-BY-3.0
      Origem: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 38,2 MB
     Runtime: org.freedesktop.Platform/x86_64/18.08
         Sdk: org.freedesktop.Sdk/x86_64/18.08

      Commit: e771cc07e99d3b42db49406d7fe2110028a71587f93b7b83ecaab42160244c33
         Pai: 2473a8d8737dcc08f14eaf955c1868f26ab1b55654ab651c508adb07d7367ff9
     Assunto: Patch AppData to add OARS (5c2e5308)
        Data: 2019-06-12 18:37:45 +0000

![2019-06-12_20-20](https://user-images.githubusercontent.com/17401812/59392945-d9f29f80-8d4f-11e9-8dbe-7c7dc7742ba6.png)
![Captura de tela_2019-06-12_20-20-10](https://user-images.githubusercontent.com/17401812/59392949-de1ebd00-8d4f-11e9-8cce-ecc8460a93de.png)

**Comment by Unrud** [comment] 2020-07-11 20:09
This seems to be a duplicate of #34

**Closed** 2020-07-11 21:09 UTC
