### ISSUE TITLE
Flatpak package creating folder outside /home/username/.var/app/ directory !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.audacityteam.Audacity#43] opened 2020-03-29 18:41 UTC
Hi. I detected that this package, when launched, creating a folder outside /home/username/.var/app/

The folder is .audacity-data & located at /home/username
 
This is unhealthy, since all things should be located within the following:
/home/username/.var/app/org.audacityteam.Audacity

Please your kind fix.

**Comment by TingPing** [comment] 2020-03-30 00:03
This is mostly a bug to report to Audacity. I imagine this was reported to them a decade ago so they might not be fans of the XDG spec.

**Comment by hfiguiere** [comment] 2020-04-21 19:12
seems like a duplicate of issue #20

**Closed** 2020-04-21 20:44 UTC
